- hosts: localhost
  connection: local
  become: yes
  become_user: sfines

  tasks:
    - include: update-ubuntu.yml
      when: ansible_os_family == 'Debian'
    
    - include: update-mac.yml
      when: ansible_os_family == 'Darwin'

    - name: Create Workspace Directory
      file:
        path: ~/workspace
        state: directory

    - name: Create Config Directory
      file:
        path: ~/.config
        state: directory

    - name: Create Install Temp Directory
      file:
        path: ~/install
        state: directory

    - name: Install dotfiles (from thoughtbot)
      git:
        repo: ssh://git@github.com/sfines/dotfiles-1.git
        dest: ~/dotfiles

    - name: Install local dotfiles
      git:
        repo: ssh://git@github.com/sfines/dotfiles-local.git
        dest: ~/dotfiles-local
        depth: 1

    - name: Install Oh My Zsh
      ansible.builtin.command:
        argv:
          - sh 
          - -c 
          - "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" 
          - "" 
          - --unattended
    - name: Install Powerlevel 10K
      git:
        repo: https://github.com/romkatv/powerlevel10k.git 
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
        depth: 1

    - name: Fetch Powerline Fonts Installer
      git:
        repo: https://github.com/powerline/fonts.git
        dest: ~/install/powerline-fonts
    
    - name: Install Powerline Fonts:
      ansible.builtin.command:
        argv:
          - /bin/bash
          - -c 
          - "$(cd ./install/powerline-fonts; ./install.sh)"

    - name: Create vimrc links
      file:
        src: "~/dotfiles/vimrc"
        dest: "~/.config/nvim/init.vim"
        state: link

    - name: Create vim bundle.links
      file:
        src: "~/dotfiles/vim"
        dest: "~/.config/nvim/vim"
        state: link
    
    - name: More bundle linking
      file:
        src: "~/dotfiles/vimrc.bundles"
        dest: "~/.vimrc.bundles"
        state: link

    - name: Install spaceemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.config/emacs

    - name: Create emacs links
      file:
        src: "~/.config/emacs"
        dest: "~/.emacs.d"
        state: link

    - name: re-generate config files
      ansible.builtin.command: 
        argv:
        - rcup


